# This file was generated by GoReleaser. DO NOT EDIT.
cask "gg" do
  version "0.35.0"

  on_macos do
    on_arm do
      sha256 "aa0b892f36bc7cf0f258da73bb1cf429a05558f7289c6857d1a7c85734a1453a"
      url "https://github.com/gagarin-cloud/gg/releases/download/v#{version}/gg_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f08cbf4d60fb8774816e07b3f00d0768b189d917e8267a3692dde5029d54d4bc"
      url "https://github.com/gagarin-cloud/gg/releases/download/v#{version}/gg_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9e5fb7e3d2a35058cbac5e63d1002fce7e8b9362bc378b7aab3935da0bade34e"
      url "https://github.com/gagarin-cloud/gg/releases/download/v#{version}/gg_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "00a8fbfba5d89e410695ae03f265bd252d557bcc7d102f89444608c2136ca79b"
      url "https://github.com/gagarin-cloud/gg/releases/download/v#{version}/gg_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gg"
  desc "The gagarin CLI — deploy and operate applications on gagarin"
  homepage "https://gagarin.cloud"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gg"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gg"]
    end
  end

  # No zap stanza required
end
