# This file was generated by GoReleaser. DO NOT EDIT.
cask "gg" do
  version "0.39.0"

  on_macos do
    on_arm do
      sha256 "44e2195a5313ec3512510136d6eb559c019281e9546c0081890963ebcf5c7d45"
      url "https://github.com/gagarin-cloud/gg/releases/download/v#{version}/gg_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "de3474f274dd11c94acd0b9f82d312885aa6ff67eb3522a19c65f3ebc10ad5b3"
      url "https://github.com/gagarin-cloud/gg/releases/download/v#{version}/gg_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "90a2fd96ffeaf67d2e74bf23ba3ab8564c92e3639dcb7bbab6a946858503c66e"
      url "https://github.com/gagarin-cloud/gg/releases/download/v#{version}/gg_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3ac36c83a72a44b7926778676a151ab12c57b79a325d697cb85d0710c3e4c683"
      url "https://github.com/gagarin-cloud/gg/releases/download/v#{version}/gg_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gg"
  desc "The gagarin CLI — deploy and operate applications on gagarin"
  homepage "https://gagarin.cloud"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gg"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gg"]
    end
  end

  # No zap stanza required
end
