# This file was generated by GoReleaser. DO NOT EDIT.
cask "gg" do
  version "0.36.0"

  on_macos do
    on_arm do
      sha256 "f16fe321ab3b1fd34d6eae9a3535120a0ad2a49c204e47d1a50e1a42df954d3d"
      url "https://github.com/gagarin-cloud/gg/releases/download/v#{version}/gg_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "807a0ba2c9d8633f9fe10a961752b8203a57db78e9586a00c4690b9199b16b58"
      url "https://github.com/gagarin-cloud/gg/releases/download/v#{version}/gg_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dc9cf3466aaa7dc61f9edd1859ce38b994aeb23ce7dcf13f5ebba54671eb6596"
      url "https://github.com/gagarin-cloud/gg/releases/download/v#{version}/gg_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d83ba46ec7656a55adf109cb2412da43b8f0ed310e84d81846fa691ddec5098c"
      url "https://github.com/gagarin-cloud/gg/releases/download/v#{version}/gg_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gg"
  desc "The gagarin CLI — deploy and operate applications on gagarin"
  homepage "https://gagarin.cloud"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gg"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gg"]
    end
  end

  # No zap stanza required
end
