# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gg < Formula
  desc "The gagarin CLI — deploy and operate applications on gagarin"
  homepage "https://gagarin.cloud"
  version "0.14.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gagarin-cloud/gg/releases/download/v0.14.2/gg_0.14.2_darwin_amd64.tar.gz"
      sha256 "709c4e076dd28e98b9057ff43b02920680b8bc68705fb7a32e60dcea4f0af9ed"

      define_method(:install) do
        bin.install "gg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gagarin-cloud/gg/releases/download/v0.14.2/gg_0.14.2_darwin_arm64.tar.gz"
      sha256 "2597d3bab3bbfba8e460eb56ca783a55c83b1e3c0f7e60982728ce88b8cdc163"

      define_method(:install) do
        bin.install "gg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gagarin-cloud/gg/releases/download/v0.14.2/gg_0.14.2_linux_amd64.tar.gz"
      sha256 "dfba22d1f69ba9f13475e76739762135d9236e30d324c0752fefcdde47bd0b8b"
      define_method(:install) do
        bin.install "gg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gagarin-cloud/gg/releases/download/v0.14.2/gg_0.14.2_linux_arm64.tar.gz"
      sha256 "75f744356799bff74d5bfcb426a43936eb44bf24a47b18c6e31d14bfd0541b3e"
      define_method(:install) do
        bin.install "gg"
      end
    end
  end

  test do
    system "#{bin}/gg", "version"
  end
end
