# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gg < Formula
  desc "The gagarin CLI — deploy and operate applications on gagarin"
  homepage "https://gagarin.cloud"
  version "0.22.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gagarin-cloud/gg/releases/download/v0.22.0/gg_0.22.0_darwin_amd64.tar.gz"
      sha256 "7912e84a18d8ec430df13a4c38bad3287cd3c4195421fbf8c011a6d2545dd93e"

      define_method(:install) do
        bin.install "gg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gagarin-cloud/gg/releases/download/v0.22.0/gg_0.22.0_darwin_arm64.tar.gz"
      sha256 "422a041df7d03d18b1fd8ad05c60ac6f1844ab28595ca64aee082491d63b729b"

      define_method(:install) do
        bin.install "gg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gagarin-cloud/gg/releases/download/v0.22.0/gg_0.22.0_linux_amd64.tar.gz"
      sha256 "d797555e3458d5619c09e1301e1978a5fe446340aeef30822d4593305684d95b"
      define_method(:install) do
        bin.install "gg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gagarin-cloud/gg/releases/download/v0.22.0/gg_0.22.0_linux_arm64.tar.gz"
      sha256 "d01cfc497b6ee121a8603074f28f2cab3ad69bc2d72927c9348a7517c6ac9bf6"
      define_method(:install) do
        bin.install "gg"
      end
    end
  end

  test do
    system "#{bin}/gg", "version"
  end
end
